apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.name | default "gitlab-pvc" }}
  namespace: {{ .Values.namespace | default .Values.persistence.namespace | default "gitlab" }}
  labels:
    app: {{ .Values.name | default "gitlab" }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "20Gi" }}
  {{ if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{ end }}
  {{ if .Values.persistence.selector }}
  selector:
    matchLabels:
      {{- range $key, $value := .Values.persistence.selector.matchLabels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{ end }}
