apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      nodePort: {{ .Values.service.ports.http.nodePort }}
    - name: ssh
      port: {{ .Values.service.ports.ssh.port }}
      targetPort: {{ .Values.service.ports.ssh.targetPort }}
      nodePort: {{ .Values.service.ports.ssh.nodePort }}
    - name: https
      port: {{ .Values.service.ports.https.port }}
      targetPort: {{ .Values.service.ports.https.targetPort }}
      nodePort: {{ .Values.service.ports.https.nodePort }}
  selector:
    app: {{ .Values.name }}
