apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name | default "postgres" }}
  namespace: {{ .Values.namespace | default .Values.postgres.service.namespace | default "gitlab" }}
  labels:
    app: {{ .Values.postgres.labels.app | default "postgres" }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.postgres.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Values.postgres.labels.app | default "postgres" }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.ports.port | default 5432 }}
      targetPort: {{ .Values.postgres.service.ports.targetPort | default 5432 }}
      name: postgres
  {{- if .Values.postgres.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.postgres.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.postgres.service.externalIPs }}
  externalIPs:
    {{- range $ip := .Values.postgres.service.externalIPs }}
    - {{ $ip }}
    {{- end }}
  {{- end }}
