apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://192.168.88.18:80'  # Замените на IP вашей ноды
                postgresql['enable'] = false
                redis['enable'] = false
                gitlab_rails['db_adapter'] = "postgresql"
                gitlab_rails['db_host'] = "postgres"
                gitlab_rails['db_port'] = 5432
                gitlab_rails['db_username'] = "postgres"
                gitlab_rails['db_password'] = "password"
                gitlab_rails['redis_host'] = "redis"
                gitlab_rails['redis_port'] = 6379
          ports:
            - containerPort: 80   
            - containerPort: 443 
            - containerPort: 22   
          volumeMounts:
            - name: gitlab-storage
              mountPath: /var/opt/gitlab
      volumes:
        - name: gitlab-storage
          persistentVolumeClaim:
            claimName: gitlab-pvc
